export const ADD_EMPLOYEE_DATA_REQUEST="ADD_EMPLOYEE_DATA_REQUEST";
export const ADD_EMPLOYEE_DATA_SUCCESS="ADD_EMPLOYEE_DATA_SUCCESS";
export const ADD_EMPLOYEE_DATA_ERROR="ADD_EMPLOYEE_DATA_ERROR";

export const GET_EMPLOYEE_DATA_REQUEST="GET_EMPLOYEE_DATA_REQUEST";
export const GET_EMPLOYEE_DATA_SUCCESS="GET_EMPLOYEE_DATA_SUCCESS";
export const GET_EMPLOYEE_DATA_ERROR="GET_EMPLOYEE_DATA_ERROR";

export const EDIT_EMPLOYEE_DATA_REQUEST="EDIT_EMPLOYEE_DATA_REQUEST";
export const EDIT_EMPLOYEE_DATA_SUCCESS="EDIT_EMPLOYEE_DATA_SUCCESS";
export const EDIT_EMPLOYEE_DATA_ERROR="EDIT_EMPLOYEE_DATA_ERROR";